# Generated by Django 3.1.4 on 2020-12-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_complate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complate',
            new_name='Bajarildi',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='prioritet',
            new_name='Prioriteti',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='Topshiriq',
        ),
    ]
